// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummerCampAPI.Models;

#nullable disable

namespace SummerCampAPI.Migrations
{
    [DbContext(typeof(RegistrationsContext))]
    [Migration("20250225160210_ChangeFK_Summer_CampsToAllowNulls")]
    partial class ChangeFK_Summer_CampsToAllowNulls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SummerCampAPI.Models.Summer_Camp_Payments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("FK_Summer_Camp_Registration")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("ID");

                    b.ToTable("Summer_Camp_Payments");
                });

            modelBuilder.Entity("SummerCampAPI.Models.Summer_Camp_Registration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CalendarYR")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("FK_Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("FK_Student_Registration__Student_ID")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("FK_Summer_Camp_Choice")
                        .HasColumnType("int");

                    b.Property<int?>("FK_Summer_Camps")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Summer_Camp_Registration");
                });

            modelBuilder.Entity("SummerCampAPI.Models.Summer_Camp_Status_History", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("FK_Summer_Camp_Registration")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Summer_Camp_Status_History");
                });

            modelBuilder.Entity("SummerCampAPI.Models.Summer_Camp_Status_Lookup", b =>
                {
                    b.Property<string>("ID_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("ID_Code");

                    b.ToTable("Summer_Camp_Status_Lookup");

                    b.HasData(
                        new
                        {
                            ID_Code = "A",
                            Desc = "(A)pplied by Parent"
                        },
                        new
                        {
                            ID_Code = "I",
                            Desc = "(I)nvited - Seat Reserved"
                        },
                        new
                        {
                            ID_Code = "C",
                            Desc = "A(C)cepted by Parent"
                        },
                        new
                        {
                            ID_Code = "R",
                            Desc = "Invitation (R)ejected by Parent"
                        },
                        new
                        {
                            ID_Code = "F",
                            Desc = "Payment (F)ailed by Parent"
                        },
                        new
                        {
                            ID_Code = "P",
                            Desc = "(P)aid by Parent"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
